export const eventsList = [
  {
    id: "7ffeb710-98cc-eaf2-2f6c-bddbecea3491",
    title: "",
    date: null,
    shortDescription: "Goldstage s’inscrit dans une continuité temporelle et produit tout spectacle musicale et one man show. La diversification du contenu à produire est une évidence chez Goldstage. Pour en savoir plus, contactez nous <a href='#contacts'>ici</a>.",
    fullDescription: "",
    location: "http://test-domain.goldstage.info",
    bannerBackground: "http://test-domain.goldstage.info/static/images/concert_sample.png",
    pictures : [],
    minTicketPrice: 50,
    maxTicketPrice: 100,
    soldOut: false,
    eventType: "music",    
  },  
  {
    id: "e69dcef0-b9b8-2f88-be79-028a75c5d8f1",
    title: "« Dance is the hidden language of the soul » — <small><i>Martha Graham</i></small>",
    date: null,
    shortDescription: "Pour Goldstage produire des ballets est une vocation. Propre à notre histoire nous produisons tous types de ballets en passant par Le Lac des signes, Casse-Noisette à Cendrillon. En étant novateur nous proposons également des ballets et des cirques sur glaces. Pour plus d’informations, contactez nous <a href='#contacts'>ici</a>.",
    fullDescription: "",
    location: "",
    bannerBackground: "http://www.danseenseine.org/wp-content/uploads/2012/12/Fille-broadcast-eng.jpg",
    pictures: [
      "http://test-domain.goldstage.info/static/images/ballet_sample.png"
    ],
    minTicketPrice: 200,
    maxTicketPrice: 600,
    soldOut: false,
    eventType: "ballet"
  },
  /*
  {
    id: "7ffeb710-98cc-eaf2-2f6c-bddbecea3491",
    title: "Beardyman",
    date: "2018-10-21",
    shortDescription: "Master cleanse try-hard woke next level franzen meditation cliche prism biodiesel distillery letterpress twee whatever fam pabst. Seitan knausgaard pabst sartorial, normcore polaroid ennui salvia swag iceland. Tacos snackwave hexagon af, normcore irony brooklyn vinyl yr letterpress. Cray wolf cred trust fund, health goth listicle occupy direct trade typewriter.",
    fullDescription: "",
    location: "http://www.beardyman.co.uk",
    bannerBackground: "https://s3-us-west-2.amazonaws.com/cc-guide-gifs/guide_gifs/hexagon+wave+-+dave+whyte.gif",
    pictures : ["https://goo.gl/GV82Tb"],
    minTicketPrice: 50,
    maxTicketPrice: 100,
    soldOut: false,
    eventType: "music",    
  },  
  {
    id: "fa557d0d-7185-28d1-9088-6341f2ce00a5",
    title: "Zemfira",
    date: new Date("2018-06-10"),
    shortDescription: "Kickstarter tofu hoodie sriracha. Raw denim four loko biodiesel ennui, wayfarers messenger bag single-origin coffee. Everyday carry gochujang taxidermy mumblecore, migas vegan art party shoreditch sriracha chambray ethical twee.",
    fullDescription: "<p>Ethical trust fund vape activated charcoal lo-fi, put a bird on it adaptogen affogato portland chambray. Fashion axe health goth chia chicharrones yr humblebrag, austin pitchfork flannel chartreuse forage tilde tattooed prism. Tumeric drinking vinegar franzen hot chicken vegan, unicorn lomo man braid. Gastropub lo-fi readymade iPhone.</p><p>Green juice tbh photo booth kale chips biodiesel distillery pitchfork selvage mlkshk vinyl messenger bag. Irony sustainable fingerstache bicycle rights chia. Poke church-key brunch edison bulb enamel pin intelligentsia tousled. Pork belly authentic neutra +1 banh mi crucifix occupy. Kitsch shabby chic 3 wolf moon, pinterest taxidermy neutra listicle copper mug mustache kale chips small batch tousled blue bottle put a bird on it. Artisan pitchfork kogi microdosing chia distillery. Forage pop-up lo-fi edison bulb.</p><p>Tote bag 8-bit austin meditation waistcoat la croix yuccie viral typewriter green juice portland vegan. Thundercats swag marfa, butcher vexillologist you probably haven't heard of them viral pok pok. Pork belly iPhone sustainable asymmetrical, ugh gluten-free selvage. Authentic pabst whatever, chambray glossier tumeric bespoke prism trust fund. Church-key affogato tousled PBR&B, gentrify hoodie fam godard retro tacos heirloom flannel. Chartreuse bicycle rights hexagon whatever flexitarian.</p>",
    location: "Imaginary street 18, Moscow, Russia",
    bannerBackground: "https://goo.gl/wkxJD5",
    pictures: [
        "https://goo.gl/NbiSPf",
        "https://goo.gl/doFvMP",
        "https://goo.gl/1sKrTP",
        "https://goo.gl/ATLjEA",
        "https://goo.gl/LRcM5e"
    ],
    minTicketPrice: 100,
    maxTicketPrice: 200,
    soldOut: false,
    eventType: "music"
  },
  {
    id: "e69dcef0-b9b8-2f88-be79-028a75c5d8f1",
    title: "La Fille du Pharaon",
    date: new Date("2018-07-21"),
    shortDescription: "Libretto by Jean-Henry Saint-Georges and Maurice Petipa after the story Le roman de la momie by Theophile Gautier, version by Pierre Lacotte",
    fullDescription: "<p>Laboris tbh DIY, coloring book ullamco vinyl magna normcore. Schlitz offal reprehenderit pop-up, tousled trust fund occupy sartorial meggings quinoa master cleanse artisan microdosing poutine. Dolor sunt ipsum flannel glossier dolore, organic artisan cornhole crucifix sint tofu offal. Copper mug polaroid cardigan, meditation poke elit enim fam cronut vexillologist wolf church-key est 3 wolf moon taxidermy. Four loko chartreuse fugiat ex semiotics fixie cronut normcore franzen. Farm-to-table sustainable gluten-free, health goth leggings vinyl austin. In locavore af cray, laboris venmo minim man bun.</p><p>Aute laborum single-origin coffee dreamcatcher venmo keffiyeh man bun proident, duis disrupt viral. Ramps mlkshk succulents narwhal, la croix aesthetic helvetica roof party whatever velit. Crucifix tousled enim pariatur readymade normcore raclette art party schlitz anim knausgaard flannel yuccie plaid lo-fi. Beard shabby chic coloring book, aliquip tattooed kale chips kickstarter whatever helvetica lyft incididunt brunch fixie semiotics tumblr. Tousled raw denim swag bicycle rights chartreuse kombucha vape kinfolk. Microdosing culpa swag yr hell of sunt, art party literally plaid ut +1 glossier vexillologist aliquip. Ipsum occupy qui, venmo taxidermy distillery migas sartorial craft beer swag proident.</p>",
    location: "Theatre Square, 1, Moscow, Russia. Historic Stage",
    bannerBackground: "http://www.danseenseine.org/wp-content/uploads/2012/12/Fille-broadcast-eng.jpg",
    pictures: [
      "https://goo.gl/4gbaFn",
      "https://goo.gl/TG2ZJa",
      "https://goo.gl/5XfZfB"
    ],
    minTicketPrice: 200,
    maxTicketPrice: 600,
    soldOut: false,
    eventType: "ballet"
  },
  {
    id: "76c45b5e-3c1c-21c8-56a7-ee3ecbb31be4",
    title: "Red Hot Chili Peppers",
    date: "2018-07-17",
    shortDescription: "Axl Rose pinterest lo-fi vexillologist franzen keffiyeh shabby chic. PBR&B chambray slow-carb thundercats, subway tile next level mumblecore keytar shabby chic tbh. Shabby chic normcore vice brooklyn occupy vexillologist blog put a bird on it retro plaid gastropub. Copper mug cornhole sartorial cred lumbersexual. Lyft pug fixie enamel pin letterpress, flannel pok pok air plant selvage adaptogen. Franzen shabby chic before they sold out pok pok distillery squid chia poke etsy pug twee.",
    fullDescription: "Celiac hella brooklyn street art 3 wolf moon, fam snackwave yuccie kale chips before they sold out brunch cornhole. Irony cloud bread put a bird on it pok pok chambray hashtag enamel pin waistcoat messenger bag adaptogen hammock neutra vice. Jianbing pitchfork microdosing, keytar brunch sriracha celiac crucifix live-edge poutine everyday carry. Readymade selvage sriracha, bushwick before they sold out direct trade vexillologist cornhole chartreuse. Cronut sriracha poke, brunch venmo swag iPhone humblebrag air plant fashion axe banjo gentrify. Edison bulb deep v 3 wolf moon pork belly schlitz.",
    location: "California",
    bannerBackground: "https://upload.wikimedia.org/wikipedia/commons/1/16/Rhcp-live-pinkpop05.jpg",
    pictures : [
      "http://www.metalsucks.net/wp-content/uploads/2014/02/Axl-Rose-and-RHCP.jpg",
      "http://assets.blabbermouth.net/media/redhotchilipeppers2016bandpressphoto_638.jpg",
      "https://assets.radiox.co.uk/2017/29/flea-red-hot-chili-peppers-responds-to-retirement-rumours-1500459755-article-0.jpg",
    ],
    minTicketPrice: 120,
    maxTicketPrice: 230,
    soldOut: false,
    eventType: "music",
  },
  {
    id: "3e8a889a-b1b7-4b48-9f6d-e594f4ecf318",
    title: "Faith No More",
    date: "2015-08-07",
    shortDescription: "Bicycle rights excepteur tattooed, blue bottle in blog consequat tofu. Semiotics twee iceland butcher, freegan esse banjo do sartorial kickstarter fingerstache poke. Asymmetrical incididunt literally helvetica, blue bottle art party echo park hoodie glossier keytar portland farm-to-table. Snackwave iceland poke bespoke ennui tofu activated charcoal mumblecore lyft.",
    fullDescription: "Four loko voluptate chicharrones, ullamco freegan dolore sartorial mixtape reprehenderit pok pok irure bespoke. DIY craft beer crucifix kinfolk. Hammock vape cardigan voluptate austin retro consequat kitsch cray banjo. Af next level copper mug, exercitation vegan tumeric esse. Tumeric actually dolore, craft beer blog ugh edison bulb offal bicycle rights flannel.",
    location: "Ricoh Coliseum, Toronto, ON, Canada",
    bannerBackground: "https://image.ibb.co/iyAgQy/faithnomore.jpg",
    pictures : [],
    minTicketPrice: 80,
    maxTicketPrice: 150,
    soldOut: true,
    eventType: "music",
  }
  */
];