export const newsList = [
  {
    "title": "Facebook Informs Data Leak Victims Whether They Need To Burn Down House, Cut Off Fingerprints, Start Anew",
    "content": "MENLO PARK, CA—Taking it upon themselves to notify users of potential repercussions stemming from the site’s recent privacy breach, Facebook announced plans Sunday to inform victims of the Cambridge Analytica data leak whether they need to burn down their houses, cut off their fingerprints, and start their lives over in a new city. “We sincerely regret allowing foreign interests to steal users’ information, and the resulting understandable breakdown in trust that has occurred, but it’s time to stop focusing on that and concentrate on whether our valued users should abandon their old lives immediately and start fresh with a totally new, unsullied identity in a place where no one will recognize them,” said CEO Mark Zuckerberg, explaining that upon logging into Facebook, each user affected by the leak will receive a simple text notification urging them to convert all their assets into cash, undergo face-altering plastic surgery, and fake their own death by stealing a body from the morgue and burning it inside a car registered in their name. “We at Facebook feel it’s important to be completely transparent with our users regarding the extent to which their data has been compromised, and we promise to do better in the future. But right now, what the affected users need to know is that they have to run. Don’t take anything you can’t grab in 90 seconds. They’re coming right now, and you don’t have much time.” At press time, a terrified Zuckerberg was spotted frantically covering his hand with lye and burning his passport after discovering his data was part of the breach.",
    "imagePath": "https://i.kinja-img.com/gawker-media/image/upload/s--_8u6PV9D--/c_scale,fl_progressive,q_80,w_800/muinigghgjcneftuhuk1.jpg"
  },
  {
    "title": "Fans Excited As ‘Solo’ Trailer Sheds Light On Specifically How It Will Suck",
    "content": "NEW YORK—Expressing their excitement at the latest preview of the upcoming film, self-proclaimed Star Wars fans told reporters Monday that they were blown away by a newly released Solo trailer that sheds light on specifically how the upcoming film will suck. “In the past, they’ve teased at the way the new movie is going to completely blow, but the full-length trailer really shows so much more about how shitty and wooden Alden Ehrenreich will be as a young Han Solo working his way through a boilerplate origin story,” said fan Lynn Hayes, noting that while the producers have provided hints at the way Solo would be a giant crock of shit—such as substantial script rewrites and the original directors being fired mid-shoot—it was a “real treat” to see the new trailer reveal so much about how the cast’s total lack of chemistry and the cringe-inducing dialogue would make the film a complete train wreck. “The teaser definitely stoked a lot of speculation about whether the movie would be mediocre because of generic characters like Therm Scissorpunch, Ron Howard’s uneven direction, or meaningless fan service like showing Chewbacca hugging his wife. It’s cool to know that it’s all of those things, and a lot more, that are really going to make this movie fucking garbage.” Hayes was, however, worried the trailer might contain spoilers that rob fans of experiencing a surge of hollow disappointment while watching Solo for the first time.",
    "imagePath": "https://i.kinja-img.com/gawker-media/image/upload/c_scale,fl_progressive,q_80,w_800/tmji6sdszng1hnc3x3em.jpg"
  },
  {
    "title": "Kobe Bryant Creates Foundation To Help Children Struggling With Severe Narcissism",
    "content": "LOS ANGELES—In an effort to destigmatize the condition of those who live with pathological self-centeredness, former basketball great Kobe Bryant held a press conference Friday to announce the launch a new foundation to help children struggling with severe narcissism. “I’ve dealt with this condition my whole life, so I feel a personal responsibility to help these kids who suffer from extreme selfishness,” said the five-time NBA champion, adding that children born without empathy should never feel ashamed, but encouraged to embrace their egotistical nature. “So many kids have to deal with grandiose views of their own talents, yet they don’t have anyone guiding them. I wish I’d had this kind of help back in high school when I was craving attention and screaming at my teammates. I’m just glad I can use my platform to teach young people that they deserve preferential treatment and constant, unwavering admiration.” Bryant added that while starting the foundation had been an amazing experience, it would have been a lot easier if the people working for him could actually follow orders and learn to do their jobs right.",
    "imagePath": "https://i.kinja-img.com/gawker-media/image/upload/c_scale,fl_progressive,q_80,w_800/b2wbimqdhjx0jf5fspnx.jpg"
  }
];